backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images"
collections:
  - name: "posts"
    label: "Blog"
    folder: "content"
    create: true
    slug: "{{titulo}}"
    fields:
      - {label: "Titulo", name: "title", widget: "string", required: true}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Descrição", name: "description", widget: "string"}
      - label: "Tipo"
        name: "type"
        widget: "select" 
        default: { label: "Post normal", value: "post" }
        options: 
          - { label: "Post normal", value: "post" }
          - { label: "Post em destaque", value: "featured" }
      - {label: "Imagem", name: "image", widget: "image"}
      - label: "Categorias"
        name: "categories"
        widget: "select"
        options: ["Blog", "Livros", "Vídeos", "Artigo", "Recomendação", "Fofoca", "Outro"]
        default: ["Blog"]
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["Famosos", "Fashion", "Fofoca", "Comida", "Fitness", "Maquiagem", "Casamento", "Música"]
      - {label: "Conteúdo", name: "body", widget: "markdown", required: true}

